global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:9090']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
